[package]
name = "dumpsync"
version = "0.1.5"
edition = "2021"
license = "MIT"
authors = ["kremilly"]
keywords = ["mysql", "dump", "restore", "backup"]
description = "A simple tool for dump and restore a MySQL database. It can be used for backup and restore purposes, or for transferring a database from one server to another."
repository = "https://github.com/kremilly/DumpSync"
documentation = "https://kremilly.com/docs/dumpsync"
homepage = "https://kremilly.com"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["cargo", "derive"] }
colored = "2.1.0"
ctrlc = "3.4.5"
dotenvy = "0.15.7"
figlet-rs = "0.1.5"
mysql = "25.0.1"
rand = "0.8.5"
