[package]
name = "dumpsync"
version = "0.1.10"
edition = "2021"
license = "MIT"
authors = ["kremilly"]
keywords = ["mysql", "dump", "restore", "backup", "database"]
description = "DumpSync is a lightweight tool designed for efficiently dumping and restoring MySQL databases. Whether you need to create backups, restore databases, or transfer data between servers."
repository = "https://github.com/kremilly/DumpSync"
documentation = "https://dumpsync.kremilly.com/"
homepage = "https://kremilly.com"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["cargo", "derive"] }
clap-cargo = "0.14.1"
colored = "2.1.0"
ctrlc = "3.4.5"
dotenvy = "0.15.7"
figlet-rs = "0.1.5"
mysql = "25.0.1"
rand = "0.8.5"
regex = "1.11.1"
reqwest = { version = "0.12.9", features = ["blocking"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
serde_yaml = "0.9.34"

[profile.release]
lto = true