name: Deploy to Vercel

on:
  push:
    branches:
      - gh-deploy  # O deploy ser치 feito apenas para essa branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Fazer o checkout do reposit칩rio
    - name: Checkout repository
      uses: actions/checkout@v3

    # Deploy na Vercel
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}  # Token da Vercel
        vercel-args: '--prod'
        working-directory: ./  # Ajuste se o diret칩rio do projeto estiver em um subdiret칩rio
