name: Deploy to Vercel

on:
  push:
    branches:
      - gh-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout do repositório
    - name: Checkout repository
      uses: actions/checkout@v3

    # Instalar dependências do projeto (Node.js exemplo)
    - name: Install dependencies
      run: npm install

    # Build do projeto
    - name: Build project
      run: npm run build

    # Deploy na Vercel
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-args: '--prod'
        working-directory: ./
